apiVersion: v1
kind: Pod
metadata:
  name: maven-test-runner
  labels:
    app: maven
    type: selenium
    admission.datadoghq.com/enabled: "true" 
    tags.datadoghq.com/env: "local"
    tags.datadoghq.com/service: "ciapp-test-kubernetes"
    tags.datadoghq.com/version: "1.0"
    ${EXTRA_POD_LABELS}
  annotations:
    # uncomment for automatic library injection
    # admission.datadoghq.com/java-lib.version: "latest"
    # js injection is kept here because it triggers volume mount, so I can test unix socket communication with the tracer I inject manually
    admission.datadoghq.com/js-lib.version: "latest"
    ${EXTRA_POD_ANNOTATIONS}
spec:
  restartPolicy: Never
  volumes:
  - name: code
    emptyDir: {}
  - name: maven-repo
    hostPath:
      path: /Users/nikita.tkachenko/.m2
  - name: report
    emptyDir: {}
  containers:
  - name: maven-test
    image: maven:3.3-jdk-8
    imagePullPolicy: IfNotPresent
    workingDir: /app/ciapp-test-resources/java/maven-junit5
    args: ["mvn", "test"]
    volumeMounts:
    - name: code
      mountPath: /app
    - name: maven-repo
      mountPath: /root/.m2
    env:
    - name: MAVEN_OPTS
      value: "${MAVEN_OPTS}"
    - name: DD_CIVISIBILITY_ENABLED
      value: "true"
    ports:
      - containerPort: 5005
  initContainers:
  - name: scm
    image: alpine/git
    imagePullPolicy: IfNotPresent
    args: ['clone', 'https://${GITHUB_TOKEN}:x-oauth-basic@github.com/DataDog/ciapp-test-resources.git']
    volumeMounts:
    - name: code
      mountPath: /git
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-pat
          key: token
