version: 2.1

orbs:
  test-visibility-circleci-orb: manueltest/test-visibility-circleci-orb@1.0.6
jobs:
  build: 
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - run:
          name: Building Code
          command: go build ./main/...
  test_additions: 
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - run:
          name: Testing Additions
          command: go test ./main/additions/...
  test_subtractions: 
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - run:
          name: Testing Subtractions
          command: go test ./main/subtractions/...
  test_python:
    working_directory: ~/repo
    docker:
      - image: python:latest
    steps:
      - checkout
      - run: apt install nodejs -y
      - run: echo "export DD_API_KEY=$PROD_DD_API_KEY" >> $BASH_ENV
      - run: pip install pytest
      - test-visibility-circleci-orb/autoinstrument:
          languages: python js
          service: js-python-autoinstrumentation
          site: datadoghq.com
      - run:
          name: Testing Python
          command: |
            DD_TRACE_DEBUG=true pytest
      - run: |
          cd node-jest
          npm run test
  custom_span: 
    working_directory: ~/repo
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: Adding custom span
          command:
            |
            npm install -g @datadog/datadog-ci
            export DD_SITE=datad0g.com
            datadog-ci trace --name "Say Hello" -- echo "Hello World"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_additions:
          requires:
            - build
      - test_subtractions:
          requires:
            - build
      - test_python:
          requires:
            - build
      - custom_span:
          requires:
            - build
